_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVSD,",
    offsets = "0,",
    addresses = "0x767,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVSD,",
    offsets = "0,",
    addresses = "0x750,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 9,
    pattern = "LLLLLLLSS",
    opcodes = "MOV,CMP,MOV,MOV,MOV,MOV,MOVSD,MOVSD,ADD,",
    offsets = "-8,-40,-8,-24,-8,-32,-16,-16,-8,",
    addresses = "0x782,0x786,0x73d,0x749,0x754,0x760,0x76f,0x778,0x77d,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 72,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 32,
    span = 40,
    head = 0,
    unroll_factor = 1,
  },
}
